### ISSUE TITLE
require_match option needs to give a person a chance to leave field blank

### ISSUE THREAD

**Issue by Stoob** [TechToThePeople/publicautocomplete#28]
Using the require_match variable doesn't allow a person to remove their input from a non-required field, and I think it should.  Is this possible to add to the code? @twomice 

Please take a look at the steps in order 1,2,3,4,5 they should explain the process when a person tries to input an employer that isn't there, and then is forced to select an employer that is there in order to submit.  What if they prefer to just leave it blank?

![1](https://user-images.githubusercontent.com/1683473/124996647-2a578c80-dffe-11eb-92a8-78115940c263.png)
![2](https://user-images.githubusercontent.com/1683473/124996655-2b88b980-dffe-11eb-92be-66840a015cc6.png)
![3](https://user-images.githubusercontent.com/1683473/124996652-2b88b980-dffe-11eb-84fd-bd330e7da666.png)
![4](https://user-images.githubusercontent.com/1683473/124996651-2af02300-dffe-11eb-9bbe-fa4abedbf5c7.png)
![5](https://user-images.githubusercontent.com/1683473/124996649-2af02300-dffe-11eb-9f7a-82198131262d.png)

**Comment by twomice** [comment]
@Stoob Yeah, good point. Funny this hasn't been mentioned until now.

Remind me please, what would be the normal behavior of CiviCRM (without this extension) if this form were submitted with blank "Current Employer" for a contact who already has a current employer relationship? Would that existing relationship be a) ignored and left unchanged, or b) removed?

**Comment by Stoob** [comment]
Whoa.  I'm not proposing any change of relationship or data.  

I'm just proposing that the form itself isn't prevented from being submitted with a blank field.

To answer your question, though, I do believe that leaving a field blank without the extension will NOT change any data, and that is fine.

**Comment by twomice** [comment]
Yep, that sounds right. The real sticking point as you say is that this extension is suddenly making it a required field even when it's not required. Let me see what we can do. 

Can you comment on urgency/timelines here? @Stoob

**Comment by Stoob** [comment]
Happy to $ sponsor.  It's not a huge issue but it is blocking some members from joining (who don't follow instructions) would be nice to have a fix within a week or so.

**Comment by twomice** [comment]
Okay, I expect we can have it for you next week. I'll try to keep this ticket informed of progress, and may reach you by email for any non-public discussion. @Stoob

**Comment by twomice** [comment]
Update for posterity:

Reproducing this bad behavior requires the following:
1. Current Employer field is a non-required field in a profile.
2. That profile is included in a Contribution page (BTW, no testing has yet been done on Event registration forms)
3. That contribution page is configured to NOT use a confirmation page.
4. The site is configured with `$civicrm_setting['eu.tttp.publicautocomplete']['require_match'] = TRUE;`

To observe the bad behavior:
1. View the live contribution page.
2. Enter a non-existent organization name (e.g. "fdsa fake organization") in the Current Employer field, and ensure all required fields are filled in.
3. Click the submit button.
4. Observe these correct and expected behaviors: the form does not submit; a pop-up message (javascript `alert()`) appears, explaining that the Current Employer must be an existing organization; the Current Employer field is bordered in red.
5. Observe this incorrect behavior: No matter what you do to the form values: the Submit button is non-responsive when clicked; the Submit button displays a "loading spinner" icon (note that the OPs site has CSS rules that hide this icon, but it is visible in the html source; and for sites lacking such custom CSS rules, the spinner is visible in the browser). The only known way to make the form work again is to reload the page in the browser.

A workaround (of admittedly questionable practicality) is to change the contribution page configuration so that it DOES use a confirmation page.

**Comment by twomice** [comment]
@Stoob , I believe we have a fix in place now. For your complete github jargon pleasure, please note: I've committed that fix to my fork, and submitted a PR to the actual repo (pr is here: https://github.com/TechToThePeople/publicautocomplete/pull/29). If Xavier doesn't have a chance to review it, I'll merge it myself in the next few days.

In the meantime, I've applied this fix to the live site, and observed good behavior in the repro steps for both your original contribution page and in my test page (see my private email with links to relevant pages and contributions).

Per the repro steps, both of those contributions were made with the "confirmation page" setting disabled.

if you would, please test for your own satisfaction when you get a chance, and post any feedback here. Thanks!
